services:
  chambre_frontend:
    image: nginx:alpine
    ports:
      - "8081:80" # <-- LE SECRET EST LÀ : On expose sur le 8081 du vieux PC
    volumes:
      - ./dist:/usr/share/nginx/html # (ou ./build si tu utilises Create React App)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always